spring:
  jpa:
      hibernate:
        ddl-auto: update
  application:
    name: order
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/db_example
    username: springuser
    password: 

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082
